version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_selection
      MYSQL_USER: test
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"